name = "Flexpart"
uuid = "fb362612-c2d8-4302-a9fd-a07f2890630f"
authors = ["Tristan Carion <tristancarion@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Debugger = "31a5f54b-26ea-5ae9-a837-f05ce5417438"

[targets]
test = ["Test"]
